<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Supplier;
use Illuminate\Support\Facades\DB;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        // DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // Supplier::truncate();
        // DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $suppliers = [
            [
                'nama_supplier' => 'PT Kimia Farma Trading & Distribution',
                'alamat' => 'Jl. Veteran No. 9, Jakarta Pusat',
                'no_telp' => '02123062973',
                'email' => 'td.kimiafarma@gmail.com',
                'kota' => 'Jakarta',
                'created_at' => now()->subMonths(24),
                'updated_at' => now()->subMonths(24),
            ],
            [
                'nama_supplier' => 'PT Anugrah Argon Medica',
                'alamat' => 'Jl. Raya Bekasi KM 21, Jakarta Timur',
                'no_telp' => '02148702525',
                'email' => 'info@aam.co.id',
                'kota' => 'Jakarta',
                'created_at' => now()->subMonths(22),
                'updated_at' => now()->subMonths(22),
            ],
            [
                'nama_supplier' => 'PT Enseval Putera Megatrading Tbk',
                'alamat' => 'Jl. Tomang Raya No. 11, Jakarta Barat',
                'no_telp' => '02156962000',
                'email' => 'customer.service@enseval.com',
                'kota' => 'Jakarta',
                'created_at' => now()->subMonths(20),
                'updated_at' => now()->subMonths(20),
            ],
            [
                'nama_supplier' => 'PT Millenium Pharmacon International',
                'alamat' => 'Jl. RS. Fatmawati No. 20, Jakarta Selatan',
                'no_telp' => '02175912929',
                'email' => 'info@mpi.co.id',
                'kota' => 'Jakarta',
                'created_at' => now()->subMonths(18),
                'updated_at' => now()->subMonths(18),
            ],
            [
                'nama_supplier' => 'PT Dankos Farma',
                'alamat' => 'Jl. Inspeksi Tarum Barat, Bekasi',
                'no_telp' => '02182430808',
                'email' => 'marketing@dankos.co.id',
                'kota' => 'Bekasi',
                'created_at' => now()->subMonths(16),
                'updated_at' => now()->subMonths(16),
            ],
            [
                'nama_supplier' => 'CV Sumber Sehat Medika',
                'alamat' => 'Jl. Mayjend Sungkono No. 89, Surabaya',
                'no_telp' => '03157484848',
                'email' => 'sumbersehat@gmail.com',
                'kota' => 'Surabaya',
                'created_at' => now()->subMonths(15),
                'updated_at' => now()->subMonths(15),
            ],
            [
                'nama_supplier' => 'PT Nusantara Farma Sejahtera',
                'alamat' => 'Jl. Gatot Subroto No. 234, Bandung',
                'no_telp' => '02287654321',
                'email' => 'nusantarafarma@yahoo.com',
                'kota' => 'Bandung',
                'created_at' => now()->subMonths(14),
                'updated_at' => now()->subMonths(14),
            ],
            [
                'nama_supplier' => 'CV Bina Farma Sejahtera',
                'alamat' => 'Jl. Pahlawan No. 123, Semarang',
                'no_telp' => '02476543210',
                'email' => 'binafarma.smg@gmail.com',
                'kota' => 'Semarang',
                'created_at' => now()->subMonths(13),
                'updated_at' => now()->subMonths(13),
            ],
            [
                'nama_supplier' => 'PT Malang Farma Distributor',
                'alamat' => 'Jl. Veteran No. 56, Malang',
                'no_telp' => '03413456789',
                'email' => 'malangfarma@outlook.com',
                'kota' => 'Malang',
                'created_at' => now()->subMonths(12),
                'updated_at' => now()->subMonths(12),
            ],
            [
                'nama_supplier' => 'CV Solo Medika Prima',
                'alamat' => 'Jl. Slamet Riyadi No. 321, Solo',
                'no_telp' => '02717654321',
                'email' => 'solomedika@gmail.com',
                'kota' => 'Solo',
                'created_at' => now()->subMonths(11),
                'updated_at' => now()->subMonths(11),
            ],
            [
                'nama_supplier' => 'PT Medan Pharma Jaya',
                'alamat' => 'Jl. Iskandar Muda No. 78, Medan',
                'no_telp' => '06178901234',
                'email' => 'medanpharma@gmail.com',
                'kota' => 'Medan',
                'created_at' => now()->subMonths(10),
                'updated_at' => now()->subMonths(10),
            ],
            [
                'nama_supplier' => 'CV Palembang Medical Supply',
                'alamat' => 'Jl. Sudirman No. 145, Palembang',
                'no_telp' => '07117890123',
                'email' => 'plg.medical@yahoo.com',
                'kota' => 'Palembang',
                'created_at' => now()->subMonths(9),
                'updated_at' => now()->subMonths(9),
            ],
            [
                'nama_supplier' => 'PT Padang Farma Utama',
                'alamat' => 'Jl. Veteran No. 234, Padang',
                'no_telp' => '07517654321',
                'email' => 'padangfarma@gmail.com',
                'kota' => 'Padang',
                'created_at' => now()->subMonths(8),
                'updated_at' => now()->subMonths(8),
            ],
            [
                'nama_supplier' => 'CV Borneo Medika',
                'alamat' => 'Jl. A. Yani No. 89, Banjarmasin',
                'no_telp' => '05113456789',
                'email' => 'borneomedika@gmail.com',
                'kota' => 'Banjarmasin',
                'created_at' => now()->subMonths(7),
                'updated_at' => now()->subMonths(7),
            ],
            [
                'nama_supplier' => 'PT Samarinda Pharma Indo',
                'alamat' => 'Jl. Mulawarman No. 156, Samarinda',
                'no_telp' => '05417890123',
                'email' => 'samarinda.pharma@yahoo.com',
                'kota' => 'Samarinda',
                'created_at' => now()->subMonths(6),
                'updated_at' => now()->subMonths(6),
            ],
            [
                'nama_supplier' => 'PT Makassar Medical Center',
                'alamat' => 'Jl. AP Pettarani No. 234, Makassar',
                'no_telp' => '04118765432',
                'email' => 'makassarmedical@gmail.com',
                'kota' => 'Makassar',
                'created_at' => now()->subMonths(5),
                'updated_at' => now()->subMonths(5),
            ],
            [
                'nama_supplier' => 'CV Manado Farma Sejahtera',
                'alamat' => 'Jl. Sam Ratulangi No. 123, Manado',
                'no_telp' => '04317654321',
                'email' => 'manadofarma@outlook.com',
                'kota' => 'Manado',
                'created_at' => now()->subMonths(4),
                'updated_at' => now()->subMonths(4),
            ],
            [
                'nama_supplier' => 'PT Bali Medika Farma',
                'alamat' => 'Jl. Sunset Road No. 567, Denpasar',
                'no_telp' => '03617890123',
                'email' => 'balimedika@gmail.com',
                'kota' => 'Denpasar',
                'created_at' => now()->subMonths(3),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'nama_supplier' => 'Toko Obat Berkah Jaya',
                'alamat' => 'Jl. Pasar Raya No. 45, Tangerang',
                'no_telp' => '02155123456',
                'email' => null,
                'kota' => 'Tangerang',
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'nama_supplier' => 'UD Sumber Rezeki Medika',
                'alamat' => 'Jl. Merdeka No. 78, Depok',
                'no_telp' => '02187654321',
                'email' => null,
                'kota' => 'Depok',
                'created_at' => now()->subMonths(1),
                'updated_at' => now()->subMonths(1),
            ],
            [
                'nama_supplier' => 'CV Mitra Farma Nusantara',
                'alamat' => 'Jl. Raya Bogor No. 234, Bogor',
                'no_telp' => '02518765432',
                'email' => 'mitrafarma.bgr@gmail.com',
                'kota' => 'Bogor',
                'created_at' => now()->subWeeks(3),
                'updated_at' => now()->subWeeks(3),
            ],
            [
                'nama_supplier' => 'Toko Grosir Obat Sehat',
                'alamat' => 'Jl. Cihampelas No. 123, Bandung',
                'no_telp' => '02220123456',
                'email' => null,
                'kota' => 'Bandung',
                'created_at' => now()->subWeeks(2),
                'updated_at' => now()->subWeeks(2),
            ],
            [
                'nama_supplier' => 'PT Indo Pharma Global',
                'alamat' => 'Jl. MT Haryono No. 456, Jakarta Selatan',
                'no_telp' => '02179123456',
                'email' => 'indopharma.global@gmail.com',
                'kota' => 'Jakarta',
                'created_at' => now()->subWeek(),
                'updated_at' => now()->subWeek(),
            ],
            [
                'nama_supplier' => 'CV Jaya Abadi Farma',
                'alamat' => 'Jl. Raya Cirebon No. 89, Cirebon',
                'no_telp' => '02313456789',
                'email' => 'jayaabadi.crb@yahoo.com',
                'kota' => 'Cirebon',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'nama_supplier' => 'Toko Farma Sejahtera',
                'alamat' => 'Jl. Ahmad Yani No. 234, Yogyakarta',
                'no_telp' => '02745678901',
                'email' => null,
                'kota' => 'Yogyakarta',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'nama_supplier' => 'PT Nusa Medika International',
                'alamat' => 'Jl. Gatot Subroto No. 789, Jakarta Selatan',
                'no_telp' => '02152123456',
                'email' => 'nusamedika@gmail.com',
                'kota' => 'Jakarta',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'nama_supplier' => 'CV Harapan Sehat Medika',
                'alamat' => 'Jl. Diponegoro No. 56, Surabaya',
                'no_telp' => '03113456789',
                'email' => 'harapansehat.sby@gmail.com',
                'kota' => 'Surabaya',
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
            ],
            [
                'nama_supplier' => 'Toko Obat Murah Berkah',
                'alamat' => 'Jl. Pasar Minggu No. 123, Jakarta Selatan',
                'no_telp' => '02178901234',
                'email' => null,
                'kota' => 'Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_supplier' => 'PT Alkes Medika Indonesia',
                'alamat' => 'Jl. Sudirman No. 567, Jakarta Pusat',
                'no_telp' => '02157890123',
                'email' => 'alkes.medika@gmail.com',
                'kota' => 'Jakarta',
                'created_at' => now()->subMonths(6),
                'updated_at' => now()->subMonths(6),
            ],
            [
                'nama_supplier' => 'PT Herbal Nusantara Sejahtera',
                'alamat' => 'Jl. Raya Solo No. 456, Solo',
                'no_telp' => '02717890123',
                'email' => 'herbalnusantara@gmail.com',
                'kota' => 'Solo',
                'created_at' => now()->subMonths(5),
                'updated_at' => now()->subMonths(5),
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }

        $this->command->info('✅ Berhasil menambahkan ' . count($suppliers) . ' data supplier!');
    }
}